- name: Deploy Vault configuration
  template:
    src: ../templates/vault.hcl.j2
    dest: "{{ vault_config_dir }}/vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_user }}"
    mode: '0640'
  notify: restart vault